export const SAVE_USER_INFO = 'SAVE_USER_INFO';

export const SET_ACTIVE_VISITOR_LOG = 'SET_ACTIVE_VISITOR_LOG';
export const LOAD_VISITOR_LOG_SUCCESS = 'LOAD_VISITOR_LOG_SUCCESS';

export default {
  SAVE_USER_INFO,
  SET_ACTIVE_VISITOR_LOG,
  LOAD_VISITOR_LOG_SUCCESS,
};
